// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbm3YTJ170T3DKRUWdEfz18-6y8aMsdwE',
    appId: '1:366819457141:web:520a56da562a8bd2e3203c',
    messagingSenderId: '366819457141',
    projectId: 'notehub-4d5ef',
    authDomain: 'notehub-4d5ef.firebaseapp.com',
    storageBucket: 'notehub-4d5ef.appspot.com',
    measurementId: 'G-WQH1717ECV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFl3GLVeAL97Awsh1shwkRGvEk9OttvhM',
    appId: '1:366819457141:android:897a9bcb2a06a8f4e3203c',
    messagingSenderId: '366819457141',
    projectId: 'notehub-4d5ef',
    storageBucket: 'notehub-4d5ef.appspot.com',
  );
}
